config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :tasks, except: [:new, :edit] do
    get 'create', on: :collection, as: 'create'
    delete 'destroy', on: :collection, as: 'destroy'
  end
  get '', to: redirect('/tasks')
  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, length: { minimum: 5, maximum: 40 }
  validates :description,  length: { minimum: 5, maximum: 500 }
  validates :priority,  numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validate :due_date_cannot_be_in_the_past
  belongs_to :user

  def due_date_cannot_be_in_the_past
    unless due_date.nil?
      unless due_date > Date.today
        errors.add(:due_date, "must be in the future")
      end
    else
      errors.add(:due_date, "can't be a blank")
    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :tasks

  def getFullName
    first_name + ' ' + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def index
    @tasks = current_user.tasks

    if params.include? :status
      if params[:status].downcase == 'active'
        @tasks = @tasks.where(is_completed: false)
      end

      if params[:status].downcase == 'completed'
        @tasks = @tasks.where(is_completed: true)
      end
    end

    if params.include? :sort
      if params[:sort].downcase == 'asc'
        @tasks = @tasks.order(Task.arel_table['title'])
      end

      if params[:sort].downcase == 'desc'
        @tasks = @tasks.order(Task.arel_table['title'].desc)
      end
    end
  end

  def create
    if params.include? :task
      @task = current_user.tasks.build(task_params)
      if @task.save
        redirect_to @task, notice: "Task was created."
      else
        render 'tasks/create'
      end
    else
      @task = current_user.tasks.build
      render 'tasks/create'
    end
  end

  def show
    begin
      @task = current_user.tasks.find(params[:id])
      if params.include? :act
        if params[:act] == 'update'
          render 'tasks/update'
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      @error = 'There is no such a task with \'id\'=\'' + params[:id] + '\'.'
      render '/tasks/error'
    end
  end

  def update
    if params.include? :act
      if params[:act] == 'complete'
        @task = current_user.tasks.find(params[:id])
        @task.update_attribute(:is_completed, !@task.is_completed)
        @act = params[:act]
        if params.include? :animate
          @animate = params[:animate]
        end
        respond_to do |format|
          format.js
        end
      end
    else
      @task = current_user.tasks.find(params[:id])
      if @task.update(task_params)
        redirect_to @task, notice: "The task was successfully updated."
      else
        render 'tasks/update'
      end
    end
  end

  def destroy
    if params.include? :tasks_to_delete
      Task.destroy(params[:tasks_to_delete])
      flash[:error] = 'Tasks were deleted.'
      redirect_back fallback_location: root_path
    else
      @task = current_user.tasks.find(params[:id])
      @task.destroy
      flash[:error] = 'Task was deleted.'
      redirect_to '/tasks'
    end
  end

  private def task_params
    params.require(:task).permit(:title, :description, :priority, :due_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {
        success: "alert-success",
        error: "alert-danger",
        danger: "alert-danger",
        alert: "alert-warning",
        notice: "alert-info",
    }[name.to_sym] || name
  end
end

app/helpers/complete_task_helper.rb
module CompleteTaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: :psj, action: action_name, controller: controller_name%>

  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Tasks management</h5>

      <nav class="my-2 my-md-0 mr-md-3">
        <% if user_signed_in? %>
          <%= link_to 'Tasks', tasks_path, :class => 'p-2 text-dark' %>
          <%= link_to 'Active tasks', tasks_path(:status => 'active'), :class => 'p-2 text-dark' %>
          <%= link_to 'Completed tasks', tasks_path(:status => 'completed'), :class => 'p-2 text-dark' %>
          <%= link_to 'New task', create_tasks_path, :class => 'p-2 text-dark' %>
          <div class="dropdown d-inline">
            <a class="p-2 text-dark dropdown-toggle" href="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name + ' ' + current_user.last_name %></a>
            <div class="dropdown-menu" aria-labelledby="dropdown09">
              <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class => 'dropdown-item' %>
            </div>
          </div>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path, :class => 'p-2 text-dark' %>
          <%= link_to 'Log In', new_user_session_path, :class => 'btn btn-primary' %>
        <% end %>
      </nav>
    </div>

    <div class="container">
      <div class="col-12">
        <% flash.each do |name, message| %>
          <div class="alert <%= bootstrap_class_for(name) %>">
            <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="col-8">
  <%= form_with model: @task, local: true do |form| %>

    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@task.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %><br>
      <%= form.text_field :title, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :description %><br>
      <%= form.text_area :description, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :priority %><br>
      <%= form.number_field :priority, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :due_date %><br>
      <%= form.date_field :due_date, :class => 'form-control' %>
    </div>
    <%= form.submit :class => 'btn btn-warning'%>

  <% end %>
</div>

app/views/tasks/_tasks_list.html.erb
<%= form_tag destroy_tasks_path,  method: :delete do %>
  <div class="d-flex justify-content-center">
      <div id="check-all-tasks" class="btn btn-link">check all</div>
      <div id="uncheck-all-tasks" class="btn btn-link">uncheck all</div>

      <% if params[:sort] %>
        <% if params[:sort]=='asc' %>
          <%= link_to 'sort ▼', params.merge(:sort => 'desc').permit(:sort, :status), class:'btn btn-link', method: :get %>
        <% end %>
        <% if params[:sort]=='desc' %>
          <%= link_to 'sort ▲', params.merge(:sort => 'asc').permit(:sort, :status), class:'btn btn-link', method: :get %>
        <% end %>
      <% else %>
        <%= link_to 'sort', params.merge(:sort => 'asc').permit(:sort, :status), class:'btn btn-link', method: :get %>
      <% end %>
  </div>
  <% @tasks.each do |task| %>
  <div class="card mb-2 task" data-task-id="<%= task.id %>">
      <div class="card-body d-flex justify-content-between">
          <div class="">
              <%= check_box_tag "tasks_to_delete[]", task.id, false,  :data => { :task_to_delete_checkbox => 'true'} %>
              <h3 class="task__title card-title d-inline-block mb-0">
                  <a class="task__title-link d-inline-block" href="<%= task_path(task.id) %>"><%= task.title %></a>
              </h3>
          </div>
          <div class="d-flex align-items-center">
              <div class="task__buttons pr-3">
                <% if params[:status] == 'completed' || params[:status] == 'active' %>
                  <% if task.is_completed %>
                    <%= link_to 'Make active', task_path(task.id, :act => 'complete', animate:'fadeout'), class:'complete-task', method: :put, remote: true %>
                  <% else %>
                    <%= link_to 'Make completed', task_path(task.id, :act => 'complete', animate:'fadeout'), class:'complete-task', method: :put, remote: true %>
                  <% end %>
                <% else %>
                  <% if task.is_completed %>
                    <%= link_to 'Make active', task_path(task.id, :act => 'complete'), class:'complete-task', method: :put, remote: true %>
                  <% else %>
                    <%= link_to 'Make completed', task_path(task.id, :act => 'complete'), class:'complete-task', method: :put, remote: true %>
                  <% end %>
                <% end %>
                <%= link_to 'edit', task_path(task.id, :act => 'update'), method: :get %>
                <%= link_to 'delete', task_path(task.id), method: :delete %>
              </div>
              <div class="task__priority">
                  <% task.priority.times do |star| %>
                  <span class="star text-orange">&#9733;</span>
                  <% end %>
                  <% (5-task.priority).times do |star| %>
                  <span class="star">&#9733;</span>
                  <% end %>
              </div>
          </div>
      </div>
  </div>
  <% end %>
  <div class="d-flex justify-content-center">
      <%= submit_tag "Delete selected", :class => 'btn btn-secondary', :id => 'delete-selected-button', :style => 'display:none' %>
  </div>
<% end %>

app/views/tasks/create.html.erb
<%= render 'form' %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/error.html.erb
<div class="container">
  <h4 class="text-center"><%= @error %></h4>
</div>

app/views/tasks/index.html.erb
<div class="col-12">
  <h2 class="text-center mx-auto mb-3">Tasks to do</h2>
  <%= render 'tasks_list' %>
</div>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="col-12">
  <div class="task card card-body mb-2">
    <div class="d-flex justify-content-between">
      <h3 class="task__title card-title">
        <a class="task__title-link" href="<%= task_path(@task.id) %>"><%= @task.title %></a>
      </h3>
      <div class="task__buttons">
        <%= link_to 'edit', task_path(:id => @task.id, :act => 'update'), method: :get  %>
        <%= link_to 'delete', task_path(@task.id), method: :delete %>
      </div>
    </div>
    <p class="task__description card-text"><%= @task.description %></p>
    <div class="d-flex justify-content-between">
      <time class="task__due-date">deadline: <%= @task.due_date.strftime("%d.%m.%Y") %></time>
      <div class="task__priority">
        <% @task.priority.times do |star| %>
          <span class="star text-orange">&#9733;</span>
        <% end %>
        <% (5-@task.priority).times do |star| %>
          <span class="star">&#9733;</span>
        <% end %>
      </div>
    </div>
  </div>
</div>



<%#= form_with(model: @task, local: true) do |form| %>

  <%# if @task.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2>-->
<!--        <%#= pluralize(@task.errors.count, "error") %> prohibited-->
<!--        this article from being saved:-->
<!--      </h2>-->
<!--      <ul>-->
        <%# @task.errors.full_messages.each do |msg| %>
<!--          <li><%#= msg %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <p>-->
<!--    <%#= form.label :title %><br>-->
    <%#= form.text_field :title %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= form.label :description %><br>-->
    <%#= form.text_area :description %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= form.label :priority %><br>-->
    <%#= form.number_field :priority, max: 5, min: 1 %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= form.label :due_date %><br>-->
    <%#= form.date_field :due_date %>
<!--  </p>-->


<!--  <p>-->
    <%#= form.submit %>
<!--  </p>-->

<%# end %>
<!--"data-provide" => "datepicker" -->

app/views/tasks/update.html.erb
<%= render 'form' %>

app/views/tasks/update.js.erb
//if(<%#= @task.is_completed %>){
//    $('.complete-task[data-task-id=<%= @task.id %>]').text('Make active');
//} else {
//    $('.complete-task[data-task-id=<%= @task.id %>]').text('Make completed');
//}

if(<%= @animate == 'fadeout' %>) {
    $('.task[data-task-id=<%= @task.id %>]').fadeOut();
} else {
  if(<%= @task.is_completed %>){
      $('.task[data-task-id=<%= @task.id %>] .complete-task')
      $('.task[data-task-id=<%= @task.id %>] .complete-task').text('Make active');
  } else {
      $('.task[data-task-id=<%= @task.id %>] .complete-task').text('Make completed');
  }
}
//console.log(<%#= params[:status] == nil %>);
//if(<%#= params[:status] == 'completed' || params[:status] == 'active' %>) {
//    console.log('111111111111111111111111111111111111')
//}
//if(Page.controller() === 'tasks' && (Page.action() == 'completed' || Page.action() == 'active')){
//    $('.task[data-task-id=<%= @task.id %>]').fadeOut();
//}
//if(Page.controller() === 'tasks' && Page.action() == 'index') {

//    if(<%#= @task.is_completed %>){
//        $('.task[data-task-id=<%= @task.id %>] .complete-task')
//        $('.task[data-task-id=<%= @task.id %>] .complete-task').text('Make active');
//    } else {
//        $('.task[data-task-id=<%= @task.id %>] .complete-task').text('Make completed');
//    }
//}

//if($('.complete-task[data-task-id=<%= @task.id %>][data-need-page-reload=true]')){
//    window.location.reload();
    //Turbolinks.visit(window.location);
//}